-- AlterTable
ALTER TABLE "form-cons" ALTER COLUMN "valor_credito" SET DATA TYPE TEXT,
ALTER COLUMN "valor_parcela" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "form-conv" ALTER COLUMN "convenio" SET DATA TYPE TEXT,
ALTER COLUMN "hospital_pref" SET DATA TYPE TEXT,
ALTER COLUMN "idade" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "form-seguro" ALTER COLUMN "peso" SET DATA TYPE TEXT,
ALTER COLUMN "altura" SET DATA TYPE TEXT,
ALTER COLUMN "fumante" SET DATA TYPE TEXT,
ALTER COLUMN "renda" SET DATA TYPE TEXT;
